"""First scheme

Revision ID: 15aaf0c4651b
Revises: None
Create Date: 2013-09-05 13:30:37.527952

"""

# revision identifiers, used by Alembic.
revision = '15aaf0c4651b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('power_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instances')
    ### end Alembic commands ###
