"""add mac address to instance

Revision ID: 1bcb98cc145f
Revises: 29ff7fd21100
Create Date: 2013-09-09 20:17:07.615269

"""

# revision identifiers, used by Alembic.
revision = '1bcb98cc145f'
down_revision = '29ff7fd21100'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances', sa.Column('mac', sa.String(length=17), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances', 'mac')
    ### end Alembic commands ###
