"""adding ipaddress table

Revision ID: 29ff7fd21100
Revises: 15aaf0c4651b
Create Date: 2013-09-05 20:02:23.048320

"""

# revision identifiers, used by Alembic.
revision = '29ff7fd21100'
down_revision = '15aaf0c4651b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipaddr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addr', sa.String(length=15), nullable=True),
    sa.Column('assigned_vm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_vm_id'], ['instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addr', name='_unique_addr')
    )
    op.alter_column(u'instances', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'instances', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('ipaddr')
    ### end Alembic commands ###
